## Collection
- string
- tuple
- list
- dict
- set


In [1]:
# Addition and subtraction
# No need to declare variable  data type.


#Variable creation 
a = 10
print(a)
b = 15
c = 20


a = b + c 
print(a)
d = 'rakesh' + ' sohil'

def add(e, f):
    a = e + f
    return a

print('run add function')
m = add(a, c)
print(m)
print(a)
print(c)

print(add('sohil', 'himansu'))
    

print(d)
print("Addition: ", a + b)
print("Substration", a - b)

# Multiplication and division
print("Multification : ", a * b)
print("Division: ", c / b)

# Exponentiation
print("10^2: ", a ** 2)

# Modulus operator

# string operators



print ()

10
35
run add function
55
35
20
sohilhimansu
rakesh sohil
Addition:  50
Substration 20
Multification :  525
Division:  1.3333333333333333
10^2:  1225



In [3]:
print(3+5)
print('rakesh ' + 'himansu')
print(3-5)
# print('rakesh' * 'himansu')
print('string substraction not supported')
print('rakesh' - 'himansu')

8
rakesh himansu
-2
string substraction not supported


TypeError: unsupported operand type(s) for -: 'str' and 'str'

# Calculations with variables
- Remember how you calculated the money you ended up with after 7 years of investing \$100? You did something like this
    * 100 \* 1.10 \**7
- Instead of calculating with the actual values, you can use variables instead. The savings variablethe $100 & create a
new variable to represent 1.10 and then redo the calculations!

In [4]:
# Create a variable savings
savings = 100

# Create a variable factor
factor = 1.10


# Calculate result
result=savings*factor**7

# Print out result
print(result)

194.87171000000012


In [5]:
factor**7

1.9487171000000012

In [6]:
factor = 2

# Other variable types
- In the previous exercise, you worked with two Python data types:
    - int, or integer: a number without a fractional part. savings, with the value 100, is an example of an integer.
    - float, or floating point: a number that has both an integer and fractional part, separated by a point. Factor, with the value 1.10, is an example of a float.
    - Next to numerical data types
- There are two other very common data types
    - str, or string: a type to represent text. You can use single or double quotes to build a string. 
    - mbool, or boolean: a type to represent logical values. Can only be True or False (the capitalization is important!).

In [7]:
# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True;

In [8]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



# Datatypes supported in Python

![title](img/py_datatypes.png)

### String and tuple

In [10]:
# String 
str1 = "python with tensorflow"
print(str1.upper())
print(str1.count('t'))
print(str1.replace('t','s'))
print(str1)

# Tuple & string
my_tuple = ("GDP",7.2,"year",2017)
print(my_tuple)
print(my_tuple*2)
print(my_tuple + ("country", 'India'))
print(my_tuple[-1])
print()



PYTHON WITH TENSORFLOW
3
pyshon wish sensorflow
python with tensorflow
('GDP', 7.2, 'year', 2017)
('GDP', 7.2, 'year', 2017, 'GDP', 7.2, 'year', 2017)
('GDP', 7.2, 'year', 2017, 'country', 'India')
2017



In [11]:
my_tuple

('GDP', 7.2, 'year', 2017)

In [12]:
my_tuple * 2

('GDP', 7.2, 'year', 2017, 'GDP', 7.2, 'year', 2017)

In [13]:
str1 * 2

'python with tensorflowpython with tensorflow'

In [14]:
my_tuple

('GDP', 7.2, 'year', 2017)

In [15]:
my_list = list(my_tuple)
my_list

['GDP', 7.2, 'year', 2017]

In [16]:
my_list[1:3]

[7.2, 'year']

In [17]:
0, 1, 2, 3

(0, 1, 2, 3)

In [18]:
my_list[-3:-1]

[7.2, 'year']

In [19]:
type(my_list)

list

In [20]:
my_list.append('sohil')
my_list

['GDP', 7.2, 'year', 2017, 'sohil']

In [21]:
my_list.count('sohil')

1

In [22]:
my_list.index('sohil')

4

In [23]:
my_tuple.count('year')

1

In [24]:
my_tuple.index('year')

2

In [26]:
for a in my_list:
    print(a)

GDP
7.2
year
2017
sohil


In [27]:
tuple1 = (1, 2, 3, 10)
for item in tuple1:
    print(item)

1
2
3
10


In [28]:
list1 = (("GDP",8.0,"year",2018))
print(list1)
print(list1 + ("country","India"))
print(list1[-1])

('GDP', 8.0, 'year', 2018)
('GDP', 8.0, 'year', 2018, 'country', 'India')
2018


In [29]:
values = [1, 20, 30, 50]
values

[1, 20, 30, 50]

In [30]:
print(len(values))
print(values[3])
print(values[0:3:3])
# 0, 1, 
print(values[0:3:1])

4
50
[1]
[1, 20, 30]


In [31]:
print(values[-1])
print(values[-2:])
print(values[-2:-1])
print(values[:])

50
[30, 50]
[30]
[1, 20, 30, 50]


In [32]:
for item in values:
    print(item)

1
20
30
50


# Dictionary and Set

# Dictionary

In [33]:
dict_mark = {"rakesh": {"math":10, "english": 9}, "Gopal": [10], "Sunil": (10, 8)}
dict_mark

{'Gopal': [10], 'Sunil': (10, 8), 'rakesh': {'english': 9, 'math': 10}}

In [34]:
dict_mark["rakesh"]['english']

9

In [35]:
dict_mark["rakesh"]["math"] = 20
dict_mark["rakesh"]["math"]

20

In [37]:
dict_mark["Sunil"][1] = 10

TypeError: 'tuple' object does not support item assignment

In [38]:
dict_mark["Gopal"][0] = 6
dict_mark["Gopal"][0]

6

In [39]:
key = dict_mark.keys()

In [40]:
type(key)

dict_keys

In [41]:
print(dict_mark)
print(dict_mark.values())
print(dict_mark.keys())
print(dict_mark.items)

{'rakesh': {'english': 9, 'math': 20}, 'Gopal': [6], 'Sunil': (10, 8)}
dict_values([{'english': 9, 'math': 20}, [6], (10, 8)])
dict_keys(['rakesh', 'Gopal', 'Sunil'])
<built-in method items of dict object at 0x0000021C90366108>


### Set

In [15]:
set1 = {10, 20, 30}

# Guess the type
- To find out the type of a value or a variable that refers to that value,
- You can use the type() function. Suppose you have defined a variable a, but you forgot the type of this variable. 
To determine the type of a, simply execute:
type(a)

In [42]:
x =15.1
y = True
print(type(x))

print(type(y))

print(type(10))

<class 'float'>
<class 'bool'>
<class 'int'>


In [44]:
print(type(values))
print(type(tuple1))
print(type(dict_mark))
print(type(factor))

<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'int'>


# Operations with other types
- When you sum two strings, for example, will get different behavior than when you sum two integers or two booleans.

        

In [45]:
# Several variables to experiment with
savings = 100
factor = 1.1
desc = "compound interest"

# Assign product of factor and savings to year1
year1 = savings*factor

# Print the type of year1

print(type(year1))
# Assign sum of desc and desc to doubledesc
doubledesc = desc+desc

# Print out doubledesc
print(doubledesc)

print(desc*2)

<class 'float'>
compound interestcompound interest
compound interestcompound interest


In [46]:
savings = 100
factor = 1.1
desc = "compound interest"
year1 = savings*factor
print(type(year1))
doubledesc = desc+desc
print(doubledesc)
print(desc*2)

<class 'float'>
compound interestcompound interest
compound interestcompound interest


In [47]:
type(year1)

float

In [48]:
print(type)

<class 'type'>


In [49]:
year2 = savings + factor
year2

101.1

In [50]:
year2

101.1

In [51]:
desc + '           ' + desc

'compound interest           compound interest'

# Type conversion
- Using the \+ operator to paste together two strings can be very useful in building custom messages.
- for example, that you have calculated the return of your investment and want to summarize the results in a string. Assuming the floats savings and result are defined, you can try something like this

In [52]:
 #Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout


# Definition of pi_string
pi_string = "3.1415926"
print(pi_string)
float(pi_string)

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
type(pi_float)

3.1415926


float

# Create a list
- A list is a compound data type; you can group values together:
    - a = "My"
    - b = "Nation"
    - my_list = ["I", "Love", a, b]
- After measuring the height of your family, you decide to collect some information on the house you are living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

In [53]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)

type(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


list

# List of lists
- You will often be dealing with a lot of data, and it will make sense to group some of this data.
- Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script on the right can already give you an idea.
- Note  "hallway" is a string, while hall is a variable that represents the float 11.25 you specified earlier.

In [54]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

float_list = ["GDP",7.5]

print(type(float_list))

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

<class 'list'>
[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


# Subset and conquer
- Subsetting Python lists is a piece of cake. Which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1.
- You can also use negative indexing.
    - x = ["a", "b", "c", "d"]
    - x[1]
    - x[-3] # same result!


In [55]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
areas[1]
print(areas[1])

# Print out last element from areas
areas[-1]
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


# Subset and calculate
- We can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:
    - x = ["a", "b", "c", "d"]
    - print(x[1] + x[3])


In [56]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area

print(eat_sleep_area)

28.75


# Slicing and dicing
- Selecting single values from a list is just one part of the story. It is also possible to slice your list, which means 
selecting multiple elements from your list. Use the following syntax:
    - my_list[start:end]
    - The start index will be included, while the end index is not.
    - list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:

In [57]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print downstairs & upstairs

print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


# Slicing and dicing(1)
my_list[begin:end]

- However, it is also possible not to specify these indexes. If you do not specify the begin index, Python figures out that you want to start your slice at the beginning of your list. If you don't specify the end index, the slice will go all the way to the last element of your list. To experiment with this, try the following commands in the IPython Shell:
    - x = ["a", "b", "c", "d"]
    - x[:2]
    - x[2:]
    - x[:]

In [58]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[6:]

print(downstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]


# Replace list elements
- Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.
- Use the IPython Shell to experiment with the commands below. Can you tell what is happening and why?
    - x = ["a", "b", "c", "d"]
    - x[1] = "r"
    - x[2:] = ["s", "t"]
    
- For this and the following exercises, you will continue working on the areas list that contains the names and areas of different rooms in a house.
- Ex. You did a miscalculation when determining the area of the bathroom; it iss 10.50 square meters instead of 9.50. Can you make the changes?
- Make the areas list more trendy! Change "living room" to "chill zone".


In [59]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


## Extend a list
- If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator:
    - x = ["a", "b", "c", "d"]
    - y = x + ["e", "f"]
- You just won the lottery, awesome! You decide to build a poolhouse and a garage. Can you add the information to the areas list?


In [60]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]
print(areas)
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


# The main difference between a list and an array
- The main difference between a list and an array is the functions that you can perform to them. 
- For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. 
- If you try to divide a list by 3, Python will tell you that it can not be done, and an error will be thrown. 

In [61]:
## math function on array##
import math
import numpy as np
import time
import sys
x = np.array([3, 6, 9, 12])
x = x/3.0
print(x)

s = range(2000)

[1. 2. 3. 4.]


# Delete list elements
- Finally, you can also remove elements from your list. You can do this with the del statement:
    - x = ["a", "b", "c", "d"]
    - del(x[1])
    - Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!
    - The updated and extended version of areas that you've built in the previous exercises is coded below. You can copy and paste this into the IPython Shell to play around with the result.

    - areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, "bedroom", 10.75, "bathroom", 10.50, "poolhouse", 24.5, "garage", 15.45]
    
    - There was a mistake! The amount you won with the lottery is not that big after all and it looks like the poolhouse is not going to happen. You decide to remove the corresponding string and float from the areas list.
    - The ; sign is used to place commands on the same line. The following two code chunks are equivalent:


In [63]:
x = ["a", "b", "c", "d"]
del(x[1])

In [64]:
x

['a', 'c', 'd']

# Familiar functions
- Out of the box, Python offers a bunch of built-in functions to make your life as a data scientist easier. 
You already know two such functions: print() and type(). You have also used the functions str(), int(), bool() and float() to switch between data types. These are built-in functions as well.
- Calling a function is easy. To get the type of 3.0 and store the output as a new variable, result, you can use the following
    - result = type(3.0)
- The general recipe for calling functions and saving the result to a variable is thus
    - output = function_name(input)
    - kichdi = coocker(dal, rise)

In [65]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


# Help!
- Maybe you already know the name of a Python function, but you still have to figure out how to use it. Ironically, you have to ask for information about a function with another function: help(). In IPython specifically, you can also use ? before the function name.
- To get help on the max() function, for example, you can use one of these calls
    - help(max)
    - ?max
- Use the Shell on the right to open up the documentation on complex(). Which of the following statements is true?

In [66]:
help(complex())
help(max)

Help on complex object:

class complex(object)
 |  complex(real[, imag]) -> complex number
 |  
 |  Create a complex number from a real part and an optional imaginary part.
 |  This is equivalent to (real + imag*1j) where imag defaults to 0.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      complex.__format__() -> str
 |      
 |      Convert to a string according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(...)
 |  
 |  __gt__(self, value, /)
 |      Re

# Multiple arguments
- The square brackets around imag in the documentation showed us that the imag argument is optional. 
But Python also uses a different way to tell users about arguments being optional.
- Have a look at the documentation of sorted() by typing help(sorted) in the IPython Shell.
- You will see that sorted() takes three arguments: iterable, key and reverse.
    - key=None means that if you do not specify the key argument, it will be None. reverse=False means that if you do not specify the reverse argument, it will be False.
    - In this exercise, you will only have to specify iterable and reverse, not key. The first input you pass to sorted() will be matched to the iterable argument, but what
    about the second input? To tell Python you want to specify reverse without changing anything about key, you can use =:
    - sorted(___, reverse = ___)
    - Two lists have been created for you on the right. Can you paste them together and sort them in descending order?
    - Note: For now, we can understand an iterable as being any collection of objects, e.g. a List.

# String Methods
- Strings come with a bunch of methods. Follow the instructions closely to discover some of them. If you want to discover them in more detail, 
you can always type help(str) in the IPython Shell.
- A string room has already been created for you to experiment with.
    - Use the upper() method on room and store the result in room_up. Use the syntax for calling methods that you learned in the previous video.
    - Print out room and room_up. Did both change?
    - Print out the number of o's on the variable room by calling count() on room and passing the letter "o" as an input to the method. We're talking about the variable room, not the word "room"!

In [67]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

In [68]:
# string to experiment with: room
room = "poolhouse"

# Use upper() on room: room_up
room_up = room.upper()

# Print out room and room_up
print(room)
print(room_up)

# Print out the number of o's in room
room.count("o")
print(room.count("o"))


poolhouse
POOLHOUSE
3


### List Methods
- Strings are not the only Python types that have methods associated with them. Lists, floats, integers and booleans are also types that come packaged with a bunch of useful methods. In this exercise, you'll be experimenting with:
- index(), to get the index of the first element of a list that matches its input and
- count(), to get the number of times an element appears in a list.
- You will be working on the list with the area of different parts of a house: areas.
- Use the index() method to get the index of the element in areas that is equal to 20.0. Print out this index
- Call count() on areas to find out how many times 14.5 appears in the list. Again, simply print out this number.

In [69]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 14.5 appears in areas
print(areas.count(14.5))


2
0


### List Methods
    - Most list methods will change the list they are called on. Examples are
    - append(), that adds an element to the list it is called on,
    - remove(), that removes the first element of a list that matches the input, and
    - reverse(), that reverses the order of the elements in the list it is called on.
    - You will be working on the list with the area of different parts of the house: areas.
### Exercise
    - Use append() twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
    - Print out areas
    - Use the reverse() method to reverse the order of the elements in areas.
    - Print out areas once more.

In [70]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


# Import package
- As a data scientist, some notions of geometry never hurt. Let us refresh some of the basics.
- For a fancy clustering algorithm, you want to find the circumference, C, and area, A, of a circle. When the radius of the circle is r, you can calculate C and A as
    - C=2πr
    - A=πr2
    - To use the constant pi, you will need the math package. A variable r is already coded in the script. Fill in the code to calculate C and A and see how the print() functions create some nice printouts.

#### Exercise
    - Import the math package. Now you can access the constant pi with math.pi.
    - Calculate the circumference of the circle and store it in C.
    - Calculate the area of the circle and store it in A.

In [71]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*0.43


# Calculate A
A = math.pi*0.43*0.43

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [72]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


# Different ways of importing
- There are several ways to import packages and modules into Python. Depending on the import call, you will have to use different Python code.
- Suppose you want to use the function inv(), which is in the linalg subpackage of the scipy package. You want to be able to use this function as follows:
- my_inv([[1,2], [3,4]])
- Which import statement will you need in order to run the above code without an error?

In [73]:
from scipy.linalg import inv as my_inv
#from scipy.linalg import my_inv
#import scipy.linalg
#import scipy


my_inv([[1,2], [3,4]])
print(my_inv)
       

<function inv at 0x0000021C906EE730>


In [74]:
a = [[1,2], [3,4]]
print(type(a))
my_inv(a)

<class 'list'>


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Your First NumPy Array
- A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

#### Example
- Import the numpy package as np, so that you can refer to numpy with np.
- Use np.array() to create a numpy array from baseball. Name this array np_baseball.
- Print out the type of np_baseball to check that you got it right.

In [76]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)


# Print out type of np_baseball
print(type(np_baseball))


<class 'numpy.ndarray'>


In [77]:
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [78]:
type(np_baseball)

numpy.ndarray

In [79]:
type(baseball)

list

In [80]:
print(baseball)

[180, 215, 210, 210, 188, 176, 209, 200]


Baseball players' height
- You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?
- height is already available and the numpy package is loaded, so you can start straight away (Source: stat.ucla.edu).

### Example
- Create a numpy array from height. Name this new array np_height. Print np_height.
- Multiply np_height with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
- Print out np_height_m and check if the output makes sense.

In [81]:
# height is available as a regular list
height = [10,20,40,80,160,320]
weight = [20, 40, 50, 50, 120, 340]
# Import numpy
import numpy as np

# Create a numpy array from height: np_height
np_height = np.array(height)

# Print out np_height
print(np_height)

# Convert np_height to m: np_height_m
np_height_m = np_height*0.0254

# Print np_height_m
print(np_height_m)

[ 10  20  40  80 160 320]
[0.254 0.508 1.016 2.032 4.064 8.128]


# Baseball player's BMI
- The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: height and weight. height is in inches and weight is in pounds.
- It is now possible to calculate the BMI of each baseball player. Python code to convert height to a numpy array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game!

In [82]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Create array from height with correct units: np_height_m
np_height_m = np.array(height) * 0.0254

# Create array from weight with correct units: np_weight_kg
np_weight_kg = np.array(weight)*0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[140.61380123  70.30690061  21.97090644   5.49272661   3.29563597
   2.33440881]


In [83]:
print(np_weight_kg)

[  9.07184  18.14368  22.6796   22.6796   54.43104 154.22128]


In [84]:
print(np_height_m)

[0.254 0.508 1.016 2.032 4.064 8.128]


In [85]:
# Lightweight baseball players

#To subset both regular Python lists and numpy arrays, you can use square brackets:

x = [4 , 9 , 6, 3, 1]
x[1]
import numpy as np
y = np.array(x)
y[1]

#For numpy specifically, you can also use boolean numpy arrays:

high = y > 5
y[high]

# The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data!

array([9, 6])

In [86]:
high

array([False,  True,  True, False, False])

In [87]:
y > 5

array([False,  True,  True, False, False])

# Exercise 
- Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.
- Print the array light.
- Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.

In [88]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2


# Create the light array
numpy = np.array(bmi) < 21
light = bmi < 21


# Print out light
print(light)


# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False False  True  True  True]
[5.49272661 3.29563597 2.33440881]


# NumPy Side Effects
- Numpy is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed
- First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.
- Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.
- Have a look at this line of code:
- np.array([True, 1, 2]) + np.array([3, 4, False])
- Can you tell which code chunk builds the exact same Python object? The numpy package is already imported as np, so you can start experimenting in the IPython Shell straight away!

In [89]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [90]:
np.array([3, 4, False])

array([3, 4, 0])

In [91]:
np.array([True, 1, 2])

array([1, 1, 2])

# Subsetting NumPy Arrays
- Python lists and numpy arrays sometimes behave differently. Luckily, there are still certainties in this world. 
- For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the IPython Shell:
    - x = ["a", "b", "c"]
    - x[1]
    - np_x = np.array(x)
    - np_x[1]
    - The script on the right already contains code that imports numpy as np, and stores both the height and weight of the MLB players as numpy arrays.

In [92]:
x = ["a", "b", "c"]
x[1]

'b'

In [93]:
np_x = np.array(x)
np_x[1]

'b'

# First 2D NumPy Array
- Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.
- In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

# Execise
- Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
- Print out the type of np_baseball.
- Print out the shape attribute of np_baseball. Use np_baseball.shape.

In [94]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


# Your First 2D NumPy Array
- Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.
- In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

In [95]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


# Baseball data in 2D form
- You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D numpy array. 
- This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).
- The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is baseball.
- Can you store the data as a 2D array to unlock numpy's extra functionality?

In [96]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


# Subsetting 2D NumPy Arrays
- If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.


# regular list of lists
    - x = [["a", "b"], ["c", "d"]]
    - [x[0][0], x[1][0]]

# numpy

- import numpy as np
- np_x = np.array(x)
- np_x[:,0]


- For regular Python lists, this is a real pain. For 2D numpy arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.
- The code that converts the pre-loaded baseball list to a 2D numpy array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 0!

In [97]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

print(np_baseball)

# Print out the 50th row of np_baseball
print(np_baseball[1])


# Select the entire second column of np_baseball: np_weight
np_weight = np_baseball[:,1]

print(np_weight)


# Print out height of 124th player
print(np_baseball[3,0])

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
[215.  102.7]
[ 78.4 102.7  98.5  75.2]
188.0


# 2D Arithmetic
- Remember how you calculated the Body Mass Index for all baseball players? numpy was able to perform all calculations element-wise (i.e. element by element). For 2D numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.
- Execute the code below in the IPython shell and see if you understand:

- import numpy as np
- np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
- np_mat * 2
- np_mat + np.array([10, 10])
- np_mat + np_mat
- np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height, weight and age.

import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat
print(np_mat)

- You managed to get hold of the changes in weight, height and age of all baseball players. It is available as a 2D numpy array, updated. 
- Add np_baseball and updated and print out the result.
- You want to convert the units of height and weight. As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
- Multiply np_baseball with conversion and print out the result.


In [98]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)
updated = np_baseball
# Print out addition of np_baseball and updated

print(np_baseball + updated)

# Create numpy array: conversion
conversion = [0.0254,0.453592,1]
conversion = np.array(conversion)
print(conversion)

[[360.  156.8]
 [430.  205.4]
 [420.  197. ]
 [376.  150.4]]
[0.0254   0.453592 1.      ]


In [99]:
np_baseball + np.array([10, 10])

array([[190. ,  88.4],
       [225. , 112.7],
       [220. , 108.5],
       [198. ,  85.2]])

In [100]:
np_baseball * 2

array([[360. , 156.8],
       [430. , 205.4],
       [420. , 197. ],
       [376. , 150.4]])

In [101]:
np_baseball + np_baseball

array([[360. , 156.8],
       [430. , 205.4],
       [420. , 197. ],
       [376. , 150.4]])

# Explore the baseball data
- Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array np_baseball, with three columns.
- The Python script on the right already includes code to print out informative messages with the different summary statistics. Can you finish the job?

- The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.
- Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.
- Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.

In [102]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


# Blend it all together
- In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.
- You've contacted FIFA for some data and they handed you two lists. The lists are the following:
    - positions = ['GK', 'M', 'A', 'D', ...]
    - heights = [191, 184, 185, 180, ...]
    - Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).
- You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

# Exercise
- Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.
- Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.
Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.
Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.
Do the same for the other players. Print out their median height. Replace None with the correct code.

In [103]:
# heights and positions are available as lists

# Import numpy
import numpy as np

positions =  ['GK', 'M', 'A']
heights = [120, 130, 140]
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 120.0
Median height of other players: 135.0
